table 85310 "Invoice Per User Buffer"
{
    Caption = 'Invoice Per User Buffer';
    DataClassification = ToBeClassified;

    fields
    {
        field(50000; "Line No"; Integer)
        {
            Caption = 'Line No';
            AutoIncrement = true;
        }
        field(50001; "Sales Invoice No"; Code[30])
        {
            Caption = 'Sales Invoice No';
        }
        field(50002; "Generated By"; Code[30])
        {
            Caption = 'Generated By';
        }
        field(50003; "Posted By"; Code[30])
        {
            Caption = 'Posted By';
        }
        field(50004; Posted; Boolean)
        {
            Caption = 'Posted Count';
            // FieldClass = FlowField;
            // CalcFormula = lookup("Sales Invoice Header"."Posted Count" where("No." = field("Sales Invoice No")));            
        }
    }
    keys
    {
        key(PK; "Line No", "Sales Invoice No")
        {
            Clustered = true;
        }
    }
}
