Report 85034 "Petty Cash Summary."
{
    ApplicationArea = All;
    UsageCategory = None;
    DefaultLayout = RDLC;
    RDLCLayout = './Layouts/Funds/PettyCashSummary..rdl';

    dataset
    {
        dataitem("Payment Line"; "Payment Line")
        {
            DataItemTableView = order(ascending) where("Pay Mode" = filter(Cash), Status = filter(Posted));
            RequestFilterFields = "Payment Type", "Paying Bank Account", "Date Posted";
            column(ReportForNavId_1000000000; 1000000000) { } // Autogenerated by ForNav - Do not delete
            column(CompInfoPicture; CompInfo.Picture)
            {
            }
            column(CompInfoName; CompInfo.Name)
            {
            }
            column(CompInfoAddress2; CompInfo."Address 2")
            {
            }
            column(Address; CompInfo.Address)
            {
            }
            column(City; CompInfo.City)
            {
            }
            column(CompInfoPostCode; CompInfo."Post Code")
            {
            }
            column(CompInfoCity; CompInfo.City)
            {
            }
            column(CompInfoPhoneNo; CompInfo."Phone No.")
            {
            }
            column(CompInfoEMail; CompInfo."E-Mail")
            {
            }
            column(CompInfoHomePage; CompInfo."Home Page")
            {
            }
            column(Reporttitle; Reporttitle)
            {
            }
            column(Mycount; Mycount)
            {
            }
            column(PaymentDesc; PaymentDesc)
            {
            }
            column(No_PaymentLinetaea; "Payment Line".No)
            {
            }
            column(PostingDate_PaymentLinetaea; "Payment Line"."Date Posted")
            {
            }
            column(LineNo_PaymentLinetaea; "Payment Line"."Line No.")
            {
            }
            column(PaymentType_PaymentLinetaea; "Payment Line"."Payment Type")
            {
            }
            column(AccountType_PaymentLinetaea; "Payment Line"."Account Type")
            {
            }
            column(AccountNo_PaymentLinetaea; "Payment Line"."Account No.")
            {
            }
            column(AccountName_PaymentLinetaea; "Payment Line"."Account Name")
            {
            }
            column(TransactionTypeDescription_PaymentLinetaea; "Payment Line"."Transaction Name")
            {
            }
            column(PaymentDescription_PaymentLinetaea; "Payment Line"."Transaction Name")
            {
            }
            column(Amount_PaymentLinetaea; "Payment Line".Amount)
            {
            }
            column(AmountLCY_PaymentLinetaea; "Payment Line".Amount)
            {
            }
            column(NetAmount_PaymentLinetaea; "Payment Line"."Net Amount")
            {
            }
            column(NetAmountLCY_PaymentLinetaea; "Payment Line"."NetAmount LCY")
            {
            }
            column(GlobalDimension1Code_PaymentLinetaea; "Payment Line"."Global Dimension 1 Code")
            {
            }
            column(GlobalDimension2Code_PaymentLinetaea; "Payment Line"."Shortcut Dimension 2 Code")
            {
            }
            column(Status_PaymentLinetaea; "Payment Line".Status)
            {
            }
            column(Posted_PaymentLinetaea; "Payment Line".Posted)
            {
            }
            column(PostedBy_PaymentLinetaea; "Payment Line"."Posted By")
            {
            }
            column(DatePosted_PaymentLinetaea; "Payment Line"."Date Posted")
            {
            }
            column(RunBalance; RunBalance)
            {
            }
            trigger OnPreDataItem();
            begin
                Reporttitle := 'Petty Cash Summary';
                Mycount := 0;
                CompInfo.Get;
                CompInfo.CalcFields(Picture);
                Clear(RunBalance);
            end;

            trigger OnAfterGetRecord();
            begin
                Mycount := Mycount + 1;
                //"Payment Line".CALCFIELDS("Payment Line"."Date Posted");
                //"Payment Line"."Posting Date2":="Payment Line"."Date Posted";
                //IF "Payment Line"."Date Posted"=0D THEN BEGIN	
                PaymentHeader.Reset;
                PaymentHeader.SetRange(PaymentHeader."No.", "Payment Line".No);
                //PaymentHeader.SETRANGE(PaymentHeader.Posted,TRUE);
                if PaymentHeader.Find('-') then begin
                    repeat
                        "Payment Line"."Date Posted" := PaymentHeader."Date Posted";
                        //"Payment Line"."Date Posted":=PaymentHeader."Date Posted";
                        //"Payment Line".Reversed:=PaymentHeader.reversed;
                        //"Payment Line"."Pay Mode":=PaymentHeader."Pay Mode";
                        //"Payment Line"."Header Date":=PaymentHeader."Document Date";
                        "Payment Line".Modify;
                        PaymentDesc := PaymentHeader.Payee;
                    until PaymentHeader.Next = 0;
                end;
                "Payment Line".Modify;
                //END;
            end;

        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
            area(Content)
            {

            }
        }

    }

    var
        PaymentHeader: Record "Payments Header";
        Reporttitle: Text;
        Mycount: Integer;
        PaymentDesc: Text;
        CompInfo: Record "Company Information";
        RunBalance: Decimal;
}
