namespace PTL.Hospital;

page 85507 "Invoice Generated By"
{
    ApplicationArea = All;
    Caption = 'Invoice Generated By';
    PageType = List;
    Editable = false;
    ModifyAllowed = false;
    InsertAllowed = false;
    DeleteAllowed = false;
    SourceTable = "Invoice Per User Buffer";
    UsageCategory = ReportsAndAnalysis;
    
    layout
    {
        area(Content)
        {
            repeater(General)
            {
                field("Sales Invoice No"; Rec."Sales Invoice No")
                {
                    ToolTip = 'Specifies the value of the Sales Invoice No field.', Comment = '%';
                }
                field("Generated By"; Rec."Generated By")
                {
                    ToolTip = 'Specifies the value of the Generated By field.', Comment = '%';
                }
                field("Posted By"; Rec."Posted By")
                {
                    ToolTip = 'Specifies the value of the Posted By field.', Comment = '%';
                }
                field(Posted; Rec.Posted)
                {
                    ToolTip = 'Specifies the value of the Posted Count field.', Comment = '%';
                }
            }
        }
    }
}
